#!/bin/bash
FIRST_LINE=$(head -n1 $(winnamelog) )
LAST_LINE=$(tail -n1 $(winnamelog) )

FIRST_TIME=$(echo "$FIRST_LINE" | sed -e "s/^[^_]*_\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\)[^0-9-].*/\1 \2 \3/")
LAST_TIME=$(echo "$LAST_LINE" | sed -e "s/^[^_]*_\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\)[^0-9-].*/\1 \2 \3/")

echo "FIRST_TIME = $FIRST_TIME"
echo "LAST_TIME = $LAST_TIME"

FIRST_TIME_H=$(echo "$FIRST_TIME" | cut -d ' ' -f 1 | sed -e "s/^[ 0]*//")
FIRST_TIME_M=$(echo "$FIRST_TIME" | cut -d ' ' -f 2 | sed -e "s/^[ 0]*//")
FIRST_TIME_H=$(( $FIRST_TIME_H ))
FIRST_TIME_M=$(( $FIRST_TIME_M ))
echo "FIRST_TIME_H = '$FIRST_TIME_H'"
echo "FIRST_TIME_M = '$FIRST_TIME_M'"

LAST_TIME_H=$(echo "$LAST_TIME" | cut -d ' ' -f 1 | sed -e "s/^[ 0]*//")
LAST_TIME_M=$(echo "$LAST_TIME" | cut -d ' ' -f 2 | sed -e "s/^[ 0]*//")
LAST_TIME_H=$(( $LAST_TIME_H ))
LAST_TIME_M=$(( $LAST_TIME_M ))
echo "LAST_TIME_H = '$LAST_TIME_H'"
echo "LAST_TIME_M = '$LAST_TIME_M'"

TOTAL_TIME_M=$(calc -p "$LAST_TIME_H*60 + $LAST_TIME_M - $FIRST_TIME_H*60 - $FIRST_TIME_M" | sed -e "s/[^0-9.]//g")
echo "TOTAL_TIME_M = '$TOTAL_TIME_M'"
echo "TOTAL_TIME =" $(($TOTAL_TIME_M / 60 )) "h" $(($TOTAL_TIME_M - $(($TOTAL_TIME_M / 60)) * 60)) "min"
echo ""

WINSUMREST=$(winsumrest2 | tail -n1 | sed -e "s/ .*//")
WINSUMREST=$(( $WINSUMREST ))
WINSUMREST_H=$(($WINSUMREST / 60))
WINSUMREST_M=$(($WINSUMREST - $WINSUMREST_H * 60))
echo "WINSUMREST = '$WINSUMREST'"
echo "WINSUMREST = $WINSUMREST_H h $WINSUMREST_M min"

INPUT_REST_TIME=$1
INPUT_REST_TIME_H=$(echo "$INPUT_REST_TIME" | sed -e "s/[^0-9]/ /g" | sed -e "s/^ *//" | sed -e "s/ \+/ /g" | cut -d ' ' -f 1 | sed -e "s/^[ 0]*//")
INPUT_REST_TIME_M=$(echo "$INPUT_REST_TIME" | sed -e "s/[^0-9]/ /g" | sed -e "s/^ *//" | sed -e "s/ \+/ /g" | cut -d ' ' -f 2 | sed -e "s/^[ 0]*//")
INPUT_REST_TIME_H=$(($INPUT_REST_TIME_H))
INPUT_REST_TIME_M=$(($INPUT_REST_TIME_M))
echo "INPUT-REST-TIME = $INPUT_REST_TIME_H h $INPUT_REST_TIME_M min"

TOTAL_TIME_NO_REST=$(($TOTAL_TIME_M - $WINSUMREST))
echo "TOTAL_TIME_NO_REST = '$TOTAL_TIME_NO_REST'"

TOTAL_TIME_NO_REST_AND_NO_INPUT_TIME_REST=$(($TOTAL_TIME_NO_REST - ($INPUT_REST_TIME_H*60) - $INPUT_REST_TIME_M))
echo "TOTAL_TIME_NO_REST_AND_NO_INPUT_TIME_REST = $TOTAL_TIME_NO_REST_AND_NO_INPUT_TIME_REST"

RESULT_TOTAL=$((6*60 - $TOTAL_TIME_NO_REST_AND_NO_INPUT_TIME_REST))
RESULT_H=$(($RESULT_TOTAL/60))
RESULT_M=$(($RESULT_TOTAL - ($RESULT_H*60) ))
echo "RESULT_TOTAL = $RESULT_TOTAL"
echo ""
echo "RESULT $RESULT_H h $RESULT_M min"

RESULT_IN_HOURS=$(calc -p "printf('%.2f', ($RESULT_H + ($RESULT_M/60)) )")
echo "RESULT_IN_HOURS = $RESULT_IN_HOURS"
