#!/bin/bash
ps ax | fgrep "python ./logger.py winlog" | fgrep -v grep| sed -e "s/^.*\(winlog_[0-9_-]\+\) .*/\1/" | while read a; do echo "open $a"; path=/home/leonid/bin/linux-app-logger/$a; cat $path; echo "===================="; tail -f $path; done 

