#!/bin/bash
ps ax | fgrep "python ./logger.py " | fgrep -v grep| sed -e "s/^.*\(winlog_[0-9_-]\+\).*/\1/" | while read a; do echo "open $a"; path=/home/leonid/worklog/$a; cat $path; echo "===================="; tail -f $path; done 

