#!/bin/sh

winchecklog > /dev/null
if [ $? != 0 ]; then
	echo "Starting the logger"
	winstartlog_always
	winchecklog
else
	echo "Logger already works"
fi

wincheckdaemonlock > /dev/null
if [ $? != 0 ]; then
	echo "Starting the daemonlock"
	winstartdaemonlock_always
	wincheckdaemonlock
else
	echo "Daemonlock already works"
fi
